site_name: Want to be a MlSys wizard
site_author: tom-jerr
site_url: https://tom-jerr.github.io
site_description: Experience the journey of a database wizard, from the basics to advanced topics.
repo_url: https://github.com/tom-jerr/tom-jerr.github.io/
repo_name: tom-jerr's Site
copyright: Copyright &copy; 2025 - Present <a href="https://github.com/tom-jerr/" target="_blank" rel="noopener">tom-jerr</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # æ—¥é—´æ¨¡å¼
      primary: white # ä¸Šæ–¹çš„
      accent: indigo # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/brightness-7 # å›¾æ ‡
        name: light mode # é¼ æ ‡æ‚¬æµ®æç¤º
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # å¤œé—´æ¨¡å¼
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: dark mode

  font:
    text: JetBrains Mono

  favicon: img/rocket.png

  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - blogging:
      locale: en
      dirs:
        - blogs/posts
      show_total: true
      features:
        tags:
          index_page: tags/
          insert: top
  - callouts
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
        - academy.md
        - links.md
        - changelog.md
  - minify:
      minify_html: true
  - mkdocs-video:
      video_muted: True
      video_controls: True
      mark: "video"
  # - rss:
  #     enabled: !ENV [CI, false]
  #     use_material_social_cards: false
  - search
  # - statistics:
  #     words_per_minute: 200

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
      linenums: true # æ˜¾ç¤ºè¡Œå·
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # - https://busuanzi.icodeq.com/busuanzi.pure.mini.js
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js

  # - js/toc.js

extra_css:
  - css/custom.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - css/fold_toc.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css
  - css/footer-stats.css

extra:
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/tom-jerr/
      name: GitHub
    - icon: /fontawesome/brands/qq
      link: /img/qq.png
      name: QQ
    - icon: /fontawesome/brands/weixin
      link: /img/wechat.png
      name: å¾®ä¿¡
    - icon: /fontawesome/brands/x-twitter
      link: https://x.com/tom_jerry_jack
      name: X
    - icon: /fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/chen-wen-de-jian-ke
      name: Zhihu
    - icon: fontawesome/solid/paper-plane
      link: mailto:2584074296@qq.com
      name: send email to me!
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_created.xml
    #   name: RSS created
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_updated.xml
    #   name: RSS updatedfeed_rss_created.xml

  analytics:
    provider: google
    property: G-NKJWZM1JHX
    feedback:
      title: Support Me!
      ratings:
        - icon: fontawesome/regular/hand-back-fist
          name: Support Me!
          data: 1
          note: >-
            <center> éš¾é“è¯´â€¦â€¦ä½ æ„¿æ„ç»™æˆ‘ä¹°ä¸€ç“¶å¿«ä¹æ°´å—ï¼ğŸ«£ </center>
            <center> How about...buy me a coffeeï¼ŸğŸ˜‹ </center>
            <img src="/img/wechat.png" width=200px>

nav:
  - Home: index.md
  - Notes:
      - index: notes/index.md
      - Python:
          - Python ä¸­çš„è£…é¥°å™¨: notes/python/Python ä¸­çš„è£…é¥°å™¨.md
          - Python ä¸­çš„å¹¶è¡Œ: notes/python/Python ä¸­çš„å¹¶è¡Œ.md
          - Asyncio åŸºç¡€: notes/python/Asyncio.md
      - tiny-llm:
          - Group Query Attention: notes/tiny-llm/Group Query Attention.md
          - RMSNorm & MLP: notes/tiny-llm/RMSNorm & MLP.md
          - Batch Inference & KV Cache: notes/tiny-llm/Batching Inference & KV Cache.md
      - cuda:
          - Roofline & Basic Analysis: notes/cuda/Roofline & Basic Analysis.md
          - Vector Add Optimization Example: notes/cuda/Vector Add Optimization Example.md
      - LLM Inference:
          - ä¸å†æ›´æ–°: blogs/llm_inference/index.md
          - Introduction for LLM Inference: blogs/llm_inference/Introduction.md
          # - CUDA Optimization: blogs/llm_inference/cudaopt.md
          - Parallelizatoin in ML System: blogs/llm_inference/parallelization.md
          - Parallelization in LLM Inference: blogs/llm_inference/LLMparallelization.md
          - PageAttention: blogs/llm_inference/pageattention.md
      - Active SLAM:
          - VINS åŸºç¡€: paperreadings/activeslam/vinsåŸºç¡€.md
          - Active SLAM æ¦‚è¿°: paperreadings/activeslam/active slam.md
      - nebula:
          - Vistor Pattern in nebula: projects/nebula-vsearch/understanding/1.visitor pattern.md
          - Memory Management in nebula: projects/nebula-vsearch/understanding/2.memory management.md
          - Concurrent LRU Cache in nebula: projects/nebula-vsearch/understanding/3.concurrent lru cache.md
          - Folly Future Promise framework in nebula: projects/nebula-vsearch/understanding/4.folly future promise.md
          - nGQL Life in Nebula: projects/nebula-vsearch/understanding/5.nGQL life.md
          - Raft Wal in Nebula: projects/nebula-vsearch/understanding/6.raft-wal.md
          - How to Modify nGQL: projects/nebula-vsearch/understanding/7.how to modify sql.md
          - A Life of KV Pairs: projects/nebula-vsearch/understandings/8.a kv life.md
      - CS61C:
          - "1 C Intro": notes/CS61C/lecture2-Intro to C.md
          - "4 C Memory Endianness": notes/CS61C/lecture4_C Memory Endianness.md
          - "10 Combinational Logic": notes/CS61C/lecture10_Combinational Logic.md
          - "11 FSMs": notes/CS61C/lecture11_FSMs.md
          - "14 Datapath": notes/CS61C/lecture14_Datapath.md
          - "15 Data-Level Parallelism": notes/CS61C/lecture15_Data-LevelParallelism.md
          - "16 Thread-Level Parallelism": notes/CS61C/lecture16_Thread-LevelParallelism.md
          - "17 Process-Level Parallelism": notes/CS61C/lecture17_Process_LevelParallelism.md
          - "18 Caches": notes/CS61C/lecture18_Caches.md
          - "21 Virtual Memory": notes/CS61C/lecture21_Virtual_Memory.md
      - CSAPP:
          - "5-ä¼˜åŒ–ç¨‹åºæ€§èƒ½": notes/CSAPP/5-ä¼˜åŒ–ç¨‹åºæ€§èƒ½.md
          - "6-å­˜å‚¨å™¨å±‚æ¬¡ç»“æ„": notes/CSAPP/6-å­˜å‚¨å™¨å±‚æ¬¡ç»“æ„.md
          - "7-é“¾æ¥": notes/CSAPP/7-é“¾æ¥.md
          - "8-å¼‚å¸¸æ§åˆ¶æµ": notes/CSAPP/8-å¼‚å¸¸æ§åˆ¶æµ.md
          - "ç¨‹åºçš„ç»“æ„å’Œæ‰§è¡Œ": notes/CSAPP/ç¨‹åºçš„ç»“æ„å’Œæ‰§è¡Œ.md
          - "åœ¨ç³»ç»Ÿä¸Šè¿è¡Œç¨‹åº": notes/CSAPP/åœ¨ç³»ç»Ÿä¸Šè¿è¡Œç¨‹åº.md
      # - rcore:
      #     - "rustlings": notes/rcore/rustlings.md
      #     - "LibOS": notes/rcore/LibOS.md
      #     - "BatchOS": notes/rcore/BatchOS.md
      #     - "TimeSharingOS": notes/rcore/TimeSharingOS.md
      - 6.s081:
          - "1 OSçš„éš”ç¦»æ€§": notes/6.s081/1-OSçš„éš”ç¦»æ€§.md
          - "2 è™šæ‹Ÿå†…å­˜å®ç°": notes/6.s081/2-è™šæ‹Ÿå†…å­˜å®ç°.md
          - "3 ç³»ç»Ÿè°ƒç”¨å’Œé™·å…¥": notes/6.s081/3-ç³»ç»Ÿè°ƒç”¨å’Œé™·å…¥.md
          - "4 ç¼ºé¡µä¸­æ–­": notes/6.s081/4-ç¼ºé¡µä¸­æ–­.md
          - "5 ç¡¬ä»¶ä¸­æ–­": notes/6.s081/5-ç¡¬ä»¶ä¸­æ–­.md
          - "6 å¤šæ ¸å’Œé”": notes/6.s081/6-å¤šæ ¸å’Œé”.md
          - "7 è¿›ç¨‹åˆ‡æ¢": notes/6.s081/7-è¿›ç¨‹åˆ‡æ¢.md
          - "8 ç¡çœ å’Œå”¤é†’": notes/6.s081/8-ç¡çœ å’Œå”¤é†’.md
      - C++ Primer:
          - "2_å˜é‡å’ŒåŸºæœ¬ç±»å‹": notes/c++primer/2_å˜é‡å’ŒåŸºæœ¬ç±»å‹.md
          - "3_å­—ç¬¦ä¸²å‘é‡æ•°ç»„": notes/c++primer/3_å­—ç¬¦ä¸²å‘é‡æ•°ç»„.md
          - "4_è¡¨è¾¾å¼": notes/c++primer/4_è¡¨è¾¾å¼.md
          - "5_è¯­å¥": notes/c++primer/5_è¯­å¥.md
          - "6_å‡½æ•°": notes/c++primer/6_å‡½æ•°.md
          - "7_ç±»": notes/c++primer/7_ç±».md
          - "8_IOåº“": notes/c++primer/8_IOåº“.md
          - "9_é¡ºåºå®¹å™¨": notes/c++primer/9_é¡ºåºå®¹å™¨.md
          - "10_æ³›å‹ç®—æ³•": notes/c++primer/10_æ³›å‹ç®—æ³•.md
          - "11_å…³è”å®¹å™¨": notes/c++primer/11_å…³è”å®¹å™¨.md
          - "12_åŠ¨æ€å†…å­˜": notes/c++primer/12_åŠ¨æ€å†…å­˜.md
          - "13_æ‹·è´æ§åˆ¶": notes/c++primer/13_æ‹·è´æ§åˆ¶.md
          - "14_é‡è½½è¿ç®—å’Œç±»å‹è½¬æ¢": notes/c++primer/14_é‡è½½è¿ç®—å’Œç±»å‹è½¬æ¢.md
          - "15_é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡": notes/c++primer/15_é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡.md
          - "å¹¶å‘ä¸å¤šçº¿ç¨‹ç¼–ç¨‹": notes/c++primer/å¹¶å‘ä¸å¤šçº¿ç¨‹ç¼–ç¨‹.md
          - "Makefileå­¦ä¹ ": notes/c++primer/Makefileå­¦ä¹ .md
      - C++ æ–°ç‰¹æ€§:
          - "1-Container": notes/C++/1-Container.md
          - "2-Algorithm": notes/C++/2-Algorithm.md
          - "3-Iterator": notes/C++/3-Iterator.md
          - "4-FileSystem": notes/C++/4-FileSystem.md
          - "5-View": notes/C++/5-View.md
          - "6-Span": notes/C++/6-Span.md
      - C++ Concurrency in Action:
          - "1-Thread": notes/C++Concurrency/1-thread.md
          - "2-Memory Model in C++": notes/C++Concurrency/2-Memory Model.md
      - CMU15445:
          - "3-Database Storage": notes/CMU15445/3-Database Storage.md
          - "4-Database_Storage_II": notes/CMU15445/4-Database_Storage_II.md
          - "5-Buffer Pool": notes/CMU15445/5-Buffer Pool.md
          - "6-Hash Table": notes/CMU15445/6-Hash Table.md
          - "7-B+Tree": notes/CMU15445/7-B+Tree.md
          - "8-Index Concurrency": notes/CMU15445/8-Index Concurrency.md
          - "9-Sort&Aggregation": notes/CMU15445/9-Sort&Aggregation.md
          - "10-Join Algorithm": notes/CMU15445/10-Join Algorithm.md
          - "11-Query_Execution": notes/CMU15445/11-Query_Execution.md
          - "12-Query_Plan&Optimization": notes/CMU15445/12-Query_Plan&Optimization.md
          - "13-Concurrency_Control_Theory": notes/CMU15445/13-Concurrency_Control_Theory.md
          - "14-Two_Phase_Lock": notes/CMU15445/14-Two_Phase_Lock.md
          - "15-Timestamp_Ordering_Concurrency": notes/CMU15445/15-Timestamp_Ordering_Concurrency.md
          - "16-Mult-Version_Concurrency": notes/CMU15445/16-Mult-Version_Concurrency.md
          - "17-Database_Logging": notes/CMU15445/17-Database_Logging.md
          - "18-Database_Recovery": notes/CMU15445/18-Database_Recovery.md
          - "19-Introducd_to_distributed_database": notes/CMU15445/19-Introducd_to_distributed_database.md
      - 6.824:
          - "MapReduce è®ºæ–‡é˜…è¯»": notes/6.824/MapReduce.md
      - Linux Tools:
          - "grep": notes/linux tools/1-grep.md
          - "sed": notes/linux tools/2-sed.md
          - "awk": notes/linux tools/3-awk.md
          - "find": notes/linux tools/4-find.md
  - PaperReading:
      - index: paperreadings/index.md
      - Database Systems:
          - Do not use MMAP in DBMS: paperreadings/db/storage/NoMMAP.md
      - Vector Search:
          - IQAN: paperreadings/vector search/IQAN.md
          - MIRAGE-ANNS: paperreadings/vector search/MIRAGE-ANNS.md
          - LSM-VEC: paperreadings/vector search/LSM-VEC.md
          - PANNS: paperreadings/vector search/PANNS.md
      - Active SLAM:
          - PL-VINS: paperreadings/activeslam/PL-VINS.md
          - 3D Active Metric-Semantic SLAM: paperreadings/activeslam/3D Active Metric-Semantic SLAM.md
          - Exploration with Global Consistency  Using Real-Time Re-integration and Active Loop Closure: paperreadings/activeslam/Exploration with Global Consistency  Using Real-Time Re-integration and Active Loop Closure.md
  - Blogs:
      - index: blogs/index.md
      - SGLang ä¸“é¢˜:
          - ä¸€æ¡ Request åœ¨ SGLang çš„å‰ä¸–ä»Šç”Ÿ: blogs/posts/ä¸€æ¡ Request åœ¨ SGLang çš„å‰ä¸–ä»Šç”Ÿ.md
          - SGLang Schedular æŠ€æœ¯å˜è¿: blogs/posts/SGLang Scheduler æŠ€æœ¯å˜è¿.md
          - DP Attention: blogs/posts/DP Attention.md
          - SGLang çš„ Cache è®¾è®¡: blogs/posts/SGLang çš„ KV Cache.md
          - ğŸš§ SGLang ä¸­çš„ Speculative Decoding: blogs/posts/SGLang ä¸­çš„ Speculative Decoding.md
      - PageAttention: blogs/posts/PageAttention.md
      - FlashAttention: blogs/posts/FlashAttention åŸç† v1-v2.md
      - Vector Add Optimization Example: blogs/posts/Vector Add Optimization Example.md
      - ä¸Šç¯‡ï¼šåˆè¯† Nebula Graph â€”â€” å‘é‡ç±»å‹æ”¯æŒ: blogs/posts/ä¸Šç¯‡ï¼šåˆè¯† Nebula Graph â€”â€” å‘é‡ç±»å‹æ”¯æŒ.md
      - ä¸­ç¯‡ï¼šVector ç±»å‹çš„ DDL & DML é€‚é…: blogs/posts/ä¸­ç¯‡ï¼šVector ç±»å‹çš„ DDL&DML é€‚é….md
      - ä¸‹ç¯‡ï¼šå‘é‡ç´¢å¼•ä¸ç›¸ä¼¼åº¦æœç´¢ â€”â€” Nebula Graph çš„ ANN å®ç°ä¹‹è·¯: blogs/posts/ä¸‹ç¯‡ï¼šå‘é‡ç´¢å¼•ä¸ç›¸ä¼¼åº¦æœç´¢ â€”â€” Nebula Graph çš„ ANN å®ç°ä¹‹è·¯.md
      - bision debug: blogs/posts/bision debug.md
      - C++ å¼‚æ­¥æ–¹æ¡ˆæ¼”è¿›: blogs/posts/C++å¼‚æ­¥æ–¹æ¡ˆ.md
      - Bustub é€šå…³æŒ‡åŒ—: blogs/posts/bustubé€šå…³æŒ‡åŒ—.md
      - å¹¶å‘ç»„ä»¶å®ç°æµ…æ: blogs/posts/Implement of Concurrent.md
      - å®ç°ä¸€ä¸ªTCP: blogs/posts/CS144.md
  - Summaries:
      - index: summary/index.md
      - "plan":
          - "ç ”ä¸€ä¸‹è§„åˆ’": summary/2025/semester-plan.md
          - "å¤§æ¨¡å‹æŠ€èƒ½æŒæ¡": summary/2025/LLM æ¨ç†ç³»ç»ŸæŠ€èƒ½å›¾è°±.md
      - "ç ”ç©¶ç”Ÿæ€»ç»“":
          - "ç ”ä¸€ä¸Šæ€»ç»“": summary/ç ”ç©¶ç”Ÿæ€»ç»“/ç ”ä¸€ä¸Šæ€»ç»“.md
          - "ç ”ä¸€ä¸‹æ€»ç»“": summary/ç ”ç©¶ç”Ÿæ€»ç»“/ç ”ä¸€ä¸‹æ€»ç»“.md
          - "ç ”äºŒä¸Šæ€»ç»“": summary/ç ”ç©¶ç”Ÿæ€»ç»“/ç ”äºŒä¸Šæ€»ç»“.md

  - Tags: tags/index.md
  - Links: links/index.md
  - About: about/index.md
