site_name: Want to be a DB wizard
site_author: tom-jerr
site_url: https://tom-jerr.github.io
site_description: Experience the journey of a database wizard, from the basics to advanced topics.
repo_url: https://github.com/tom-jerr/tom-jerr.github.io/
repo_name: tom-jerr's Site
copyright: Copyright &copy; 2025 - Present <a href="https://github.com/tom-jerr/" target="_blank" rel="noopener">tom-jerr</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # æ—¥é—´æ¨¡å¼
      primary: white # ä¸Šæ–¹çš„
      accent: indigo # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/brightness-7 # å›¾æ ‡
        name: light mode # é¼ æ ‡æ‚¬æµ®æç¤º
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # å¤œé—´æ¨¡å¼
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: dark mode

  font:
    text: JetBrains Mono

  favicon: img/rocket.png

  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - blogging:
      locale: en
      dirs:
        - blogs/posts
      show_total: true
      features:
        tags:
          index_page: tags/
          insert: top
  - callouts
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
        - academy.md
        - links.md
        - changelog.md
  - minify:
      minify_html: true
  - mkdocs-video:
      video_muted: True
      video_controls: True
      mark: "video"
  # - rss:
  #     enabled: !ENV [CI, false]
  #     use_material_social_cards: false
  - search
  - statistics:
      words_per_minute: 200

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
      linenums: true # æ˜¾ç¤ºè¡Œå·
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # - https://busuanzi.icodeq.com/busuanzi.pure.mini.js
  - js/mathjax.js
  # - js/toc.js

extra_css:
  - css/custom.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - css/fold_toc.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css

extra:
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/tom-jerr/
      name: GitHub
    - icon: /fontawesome/brands/qq
      link: /img/qq.png
      name: QQ
    - icon: /fontawesome/brands/weixin
      link: /img/wechat.png
      name: å¾®ä¿¡
    - icon: /fontawesome/brands/x-twitter
      link: https://x.com/tom_jerry_jack
      name: X
    - icon: /fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/chen-wen-de-jian-ke
      name: Zhihu
    - icon: fontawesome/solid/paper-plane
      link: mailto:2584074296@qq.com
      name: send email to me!
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_created.xml
    #   name: RSS created
    # - icon: fontawesome/solid/rss
    #   link: /feed_rss_updated.xml
    #   name: RSS updatedfeed_rss_created.xml

  analytics:
    provider: google
    property: G-20LWGZNLLR
    feedback:
      title: Support Me!
      ratings:
        - icon: fontawesome/regular/hand-back-fist
          name: Support Me!
          data: 1
          note: >-
            <center> éš¾é“è¯´â€¦â€¦ä½ æ„¿æ„ç»™æˆ‘ä¹°ä¸€ç“¶å¿«ä¹æ°´å—ï¼ğŸ«£ </center>
            <center> How about...buy me a coffeeï¼ŸğŸ˜‹ </center>
            <img src="https://cdn.jsdelivr.net/gh/KinnariyaMamaTanha/Images@images/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_2024-12-07_230055_143.png" width=200px>

nav:
  - Home: index.md
  - Notes:
      - index: notes/index.md
      - CS61C:
          - "1 C Intro": notes/CS61C/lecture2-Intro to C.md
          - "4 C Memory Endianness": notes/CS61C/lecture4_C Memory Endianness.md
          - "10 Combinational Logic": notes/CS61C/lecture10_Combinational Logic.md
          - "11 FSMs": notes/CS61C/lecture11_FSMs.md
          - "14 Datapath": notes/CS61C/lecture14_Datapath.md
          - "15 Data-Level Parallelism": notes/CS61C/lecture15_Data-LevelParallelism.md
          - "16 Thread-Level Parallelism": notes/CS61C/lecture16_Thread-LevelParallelism.md
          - "17 Process-Level Parallelism": notes/CS61C/lecture17_Process_LevelParallelism.md
          - "18 Caches": notes/CS61C/lecture18_Caches.md
          - "21 Virtual Memory": notes/CS61C/lecture21_Virtual_Memory.md

      - CSAPP:
          - "5-ä¼˜åŒ–ç¨‹åºæ€§èƒ½": notes/CSAPP/5-ä¼˜åŒ–ç¨‹åºæ€§èƒ½.md
          - "6-å­˜å‚¨å™¨å±‚æ¬¡ç»“æ„": notes/CSAPP/6-å­˜å‚¨å™¨å±‚æ¬¡ç»“æ„.md
          - "7-é“¾æ¥": notes/CSAPP/7-é“¾æ¥.md
          - "8-å¼‚å¸¸æ§åˆ¶æµ": notes/CSAPP/8-å¼‚å¸¸æ§åˆ¶æµ.md
          - "ç¨‹åºçš„ç»“æ„å’Œæ‰§è¡Œ": notes/CSAPP/ç¨‹åºçš„ç»“æ„å’Œæ‰§è¡Œ.md
          - "åœ¨ç³»ç»Ÿä¸Šè¿è¡Œç¨‹åº": notes/CSAPP/åœ¨ç³»ç»Ÿä¸Šè¿è¡Œç¨‹åº.md

      - rcore:
          - "rustlings": notes/rcore/rustlings.md
          - "LibOS": notes/rcore/LibOS.md
          - "BatchOS": notes/rcore/BatchOS.md
          - "TimeSharingOS": notes/rcore/TimeSharingOS.md

      - 6.s081:
          - "1 OSçš„éš”ç¦»æ€§": notes/6.s081/1-OSçš„éš”ç¦»æ€§.md
          - "2 è™šæ‹Ÿå†…å­˜å®ç°": notes/6.s081/2-è™šæ‹Ÿå†…å­˜å®ç°.md
          - "3 ç³»ç»Ÿè°ƒç”¨å’Œé™·å…¥": notes/6.s081/3-ç³»ç»Ÿè°ƒç”¨å’Œé™·å…¥.md
          - "4 ç¼ºé¡µä¸­æ–­": notes/6.s081/4-ç¼ºé¡µä¸­æ–­.md
          - "5 ç¡¬ä»¶ä¸­æ–­": notes/6.s081/5-ç¡¬ä»¶ä¸­æ–­.md
          - "6 å¤šæ ¸å’Œé”": notes/6.s081/6-å¤šæ ¸å’Œé”.md
          - "7 è¿›ç¨‹åˆ‡æ¢": notes/6.s081/7-è¿›ç¨‹åˆ‡æ¢.md
          - "8 ç¡çœ å’Œå”¤é†’": notes/6.s081/8-ç¡çœ å’Œå”¤é†’.md

      - C++ Primer:
          - "2_å˜é‡å’ŒåŸºæœ¬ç±»å‹": notes/c++primer/2_å˜é‡å’ŒåŸºæœ¬ç±»å‹.md
          - "3_å­—ç¬¦ä¸²å‘é‡æ•°ç»„": notes/c++primer/3_å­—ç¬¦ä¸²å‘é‡æ•°ç»„.md
          - "4_è¡¨è¾¾å¼": notes/c++primer/4_è¡¨è¾¾å¼.md
          - "5_è¯­å¥": notes/c++primer/5_è¯­å¥.md
          - "6_å‡½æ•°": notes/c++primer/6_å‡½æ•°.md
          - "7_ç±»": notes/c++primer/7_ç±».md
          - "8_IOåº“": notes/c++primer/8_IOåº“.md
          - "9_é¡ºåºå®¹å™¨": notes/c++primer/9_é¡ºåºå®¹å™¨.md
          - "10_æ³›å‹ç®—æ³•": notes/c++primer/10_æ³›å‹ç®—æ³•.md
          - "11_å…³è”å®¹å™¨": notes/c++primer/11_å…³è”å®¹å™¨.md
          - "12_åŠ¨æ€å†…å­˜": notes/c++primer/12_åŠ¨æ€å†…å­˜.md
          - "13_æ‹·è´æ§åˆ¶": notes/c++primer/13_æ‹·è´æ§åˆ¶.md
          - "14_é‡è½½è¿ç®—å’Œç±»å‹è½¬æ¢": notes/c++primer/14_é‡è½½è¿ç®—å’Œç±»å‹è½¬æ¢.md
          - "15_é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡": notes/c++primer/15_é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡.md
          - "å¹¶å‘ä¸å¤šçº¿ç¨‹ç¼–ç¨‹": notes/c++primer/å¹¶å‘ä¸å¤šçº¿ç¨‹ç¼–ç¨‹.md
          - "Makefileå­¦ä¹ ": notes/c++primer/Makefileå­¦ä¹ .md

      - C++ æ–°ç‰¹æ€§:
          - "1-Container": notes/C++/1-Container.md
          - "2-Algorithm": notes/C++/2-Algorithm.md
          - "3-Iterator": notes/C++/3-Iterator.md
          - "4-FileSystem": notes/C++/4-FileSystem.md
          - "5-View": notes/C++/5-View.md
          - "6-Span": notes/C++/6-Span.md

      - C++ Concurrency in Action:
          - "1-Thread": notesC++Concurrency/1-thread.md
          - "2-Memory Model in C++": notes/C++Concurrency/2-Memory Model.md

      - CMU15445:
          - "3-Database Storage": notes/CMU15445/3-Database Storage.md
          - "4-Database_Storage_II": notes/CMU15445/4-Database_Storage_II.md
          - "5-Buffer Pool": notes/CMU15445/5-Buffer Pool.md
          - "6-Hash Table": notes/CMU15445/6-Hash Table.md
          - "7-B+Tree": notes/CMU15445/7-B+Tree.md
          - "8-Index Concurrency": notes/CMU15445/8-Index Concurrency.md
          - "9-Sort&Aggregation": notes/CMU15445/9-Sort&Aggregation.md
          - "10-Join Algorithm": notes/CMU15445/10-Join Algorithm.md
          - "11-Query_Execution": notes/CMU15445/11-Query_Execution.md
          - "12-Query_Plan&Optimization": notes/CMU15445/12-Query_Plan&Optimization.md
          - "13-Concurrency_Control_Theory": notes/CMU15445/13-Concurrency_Control_Theory.md
          - "14-Two_Phase_Lock": notes/CMU15445/14-Two_Phase_Lock.md
          - "15-Timestamp_Ordering_Concurrency": notes/CMU15445/15-Timestamp_Ordering_Concurrency.md
          - "16-Mult-Version_Concurrency": notes/CMU15445/16-Mult-Version_Concurrency.md
          - "17-Database_Logging": notes/CMU15445/17-Database_Logging.md
          - "18-Database_Recovery": notes/CMU15445/18-Database_Recovery.md
          - "19-Introducd_to_distributed_database": notes/CMU15445/19-Introducd_to_distributed_database.md

      - 6.824:
          - "MapReduce è®ºæ–‡é˜…è¯»": notes/6.824/MapReduce.md

      - minilsm:
          - "week1-day1": notes/minilsm/week1-day1.md
          - "week1-day2": notes/minilsm/week1-day2.md
          - "week1-day3": notes/minilsm/week1-day3.md
          - "week1-day4": notes/minilsm/week1-day4.md

  - Blogs:
      - index: blogs/index.md
      - å®ç°ä¸€ä¸ªTCP: blogs/posts/CS144/CS144.md
      - bision debug: blogs/posts/bision debug.md
      - Bustub é€šå…³æŒ‡åŒ—: blogs/bustubé€šå…³æŒ‡åŒ—.md
      - C++ å¼‚æ­¥æ–¹æ¡ˆæ¼”è¿›: blogs/C++å¼‚æ­¥æ–¹æ¡ˆ.md
      - å¹¶å‘ç»„ä»¶å®ç°æµ…æ: blogs/Implement of Concurrent.md
      - ospp-nebula:
          - UnderStanding:
              - Vistor Pattern in nebula: notes/nebula/1.visitor pattern.md
              - Memory Management in nebula: notes/nebula/2.memory management.md
              - Concurrent LRU Cache in nebula: notes/nebula/3.concurrent lru cache.md
              - Folly Future Promise framework in nebula: notes/nebula/4.folly future promise.md
              - nGQL Life in Nebula: notes/nebula/5.nGQL life.md
              - Raft Wal in Nebula: notes/nebula/6.raft-wal.md
              - How to Modify nGQL: notes/nebula/7.how to modify sql.md
              - A Life of KV Pairs: blogs/posts/ospp-nebula/understandings/a kv life.md
          - Implement:
              - DDL for VECTOR Type: blogs/posts/ospp-nebula/implements/DDL for vector type.md
              - DML for VECTOR Type: blogs/posts/ospp-nebula/implements/DML for vector type.md
              - Match for VECTOR Type: blogs/posts/ospp-nebula/implements/Match for vector property.md
      - Linux Tools:
          - "grep": blogs/linux tools/1-grep.md
          - "sed": blogs/linux tools/2-sed.md
          - "awk": blogs/linux tools/3-awk.md
          - "find": blogs/linux tools/4-find.md
      - vector search papers:
          - "LSM-VEC": blogs/paper notes/vector search/LSM-VEC.md
          - "iQAN": blogs/paper notes/vector search/IQAN.md

  - Summaries:
      - index: summary/index.md
      - "2025":
          - "ç ”ä¸€ä¸‹è§„åˆ’": summary/2025/semester-plan.md
  - Tags: tags/index.md
  - Links: links/index.md
  - About: about/index.md
